sudo: false
dist: xenial

language: python
cache: pip

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

env:
  matrix:
    - CLICK_VERSION=4.1
    - CLICK_VERSION=5.1
    - CLICK_VERSION=6.7
    - CLICK_VERSION=7

install:
  - pip install coveralls
  - pip install -e ".[dev]"
  - pip install "click==${CLICK_VERSION}"

script:
  - pytest tests --cov click_plugins --cov-report term-missing

after_success:
  - coveralls
